# Generated by Django 5.2.7 on 2025-10-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
