# Generated by Django 5.2.7 on 2025-10-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="course/images"),
        ),
    ]
