# Generated by Django 5.2.7 on 2025-10-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(max_length=800),
        ),
    ]
